### PR TITLE
Revert "Temporarily restore Thread/ThreadGroup suspend/resume/stop"

### PR DESCRIPTION
**Pull request by LongyuZhang**
- Revert https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/729
Related Issue: https://github.com/eclipse-openj9/openj9/issues/18758

### CODE REVIEW

**Comment by LongyuZhang** [comment]
The copyright year has been updated. Thanks.

**Comment by llxia** [comment]
@LongyuZhang could you please push again to trigger Copyright check? Thanks

**Comment by LongyuZhang** [comment]
> @LongyuZhang could you please push again to trigger Copyright check? Thanks

Similar to https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/729#issuecomment-1895793736, the copyright is appropriate given all the code is from upstream. Thanks.

**Comment by keithc-ca** [comment]
> This is a revert of [ibmruntimes/openj9-openjdk-jdk#729](https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/729)

I think that should be the summary of this change.

**Comment by LongyuZhang** [comment]
> > This is a revert of [ibmruntimes/openj9-openjdk-jdk#729](https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/729)
> 
> I think that should be the summary of this change.

Updated the description. Thanks.

**Comment by keithc-ca** [comment]
Same comment here about commit message: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/818#issuecomment-2258423366.

**Comment by LongyuZhang** [comment]
> Same comment here about commit message: [ibmruntimes/openj9-openjdk-jdk#818 (comment)](https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/818#issuecomment-2258423366).

Updated the commit description as above. Thanks.

**Comment by keithc-ca** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/818#issuecomment-2258703711 applies here as well.

**Comment by LongyuZhang** [comment]
> [ibmruntimes/openj9-openjdk-jdk#818 (comment)](https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/818#issuecomment-2258703711) applies here as well.

Updated. Thanks.

**Comment by keithc-ca** [comment]
Jenkins test sanity zlinux jdk23

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
