### PR TITLE
(v0.47.0) CRIU supports Java debugger during checkpoint and restore

### PR DESCRIPTION
**Pull request by JasonFengJ9**
CRIU supports Java debugger during checkpoint and restore

Added support for a `VM_RESTORE` `JVMTI` event;
Added command line option `suspendOnRestore=[y|n]` to determine if the VM restored from a checkpoint is to be suspended;
`-agentlib:jdwp=transport=dt_socket,server=y,suspend=[y|n]` assumes `suspendOnRestore=y`;
Always respect `suspendOnRestore=n` regardless the order of `suspend` and `suspendOnRestore`, both
`-agentlib:jdwp=transport=dt_socket,server=y,suspendOnRestore=n,suspend=y` and `-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,suspendOnRestore=n` don't suspend the JVM post-restore.

Cherry-pick
* https://github.com/ibmruntimes/openj9-openjdk-jdk23/pull/34

Signed-off-by: Mike Zhang <mike.h.zhang@ibm.com>
Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
It's too late to accept anything except no risk changes for 0.47. We're about to start RC1 later today or tomorrow.

**Comment by pshipton** [comment]
@tajila any reason we should include this in the Java 21 GA? There will be a refresh in Oct that includes the change.

**Comment by JasonFengJ9** [comment]
> any reason we should include this in the Java 21 GA?

I guess you meant Java 23, right?

**Comment by pshipton** [comment]
We are trying to fast track it to meet the Sep 17 GA.

**Comment by JasonFengJ9** [comment]
Okay, this can be included in 0.48 instead.

**Comment by tajila** [comment]
Yes we can add these changes to 0.48

**Pull request closed without merging**
