### PR TITLE
Update the ignore list based on RC1

### PR DESCRIPTION
**Pull request by JinhangZhang**
Update the ignore list based on RC1 results among various platforms.

### CODE REVIEW

**Comment by keithc-ca** [comment]
Please create an appropriate change for https://github.com/ibmruntimes/openj9-openjdk-jdk which should be merged before this is considered.

**Review by keithc-ca — CHANGES_REQUESTED** [review]
Please remove line 475 which seems to be redundant given line 474.

**Comment by JinhangZhang** [comment]
Removed

> Please remove line 475 which seems to be redundant given line 474.

**Comment by keithc-ca** [comment]
Jenkins test sanity zlinux jdk23

**Pull request merged**
