### PR TITLE
Update FIPS140-3 exclusions with Windows

### PR DESCRIPTION
**Pull request by JinhangZhang**
Add failures shows up in the windows platform.

Cherry-pick from https://github.com/ibmruntimes/openj9-openjdk-jdk23/pull/29

### CODE REVIEW

**Comment by JinhangZhang** [comment]
@jasonkatonica @llxia FYI

**Comment by llxia** [comment]
Is this cherry pick of https://github.com/ibmruntimes/openj9-openjdk-jdk23/pull/29?

**Comment by JinhangZhang** [comment]
> Is this cherry pick of #29?

Yes

**Comment by llxia** [comment]
@keithc-ca could you review? Thanks

**Review by keithc-ca — APPROVED** [review]

**Comment by keithc-ca** [comment]
Jenkins copyright check

**Comment by keithc-ca** [comment]
Jenkins line endings check

**Pull request merged**
